# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
Title:          My Blog
paginate:       5

url:            "https://username.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:: compressed

# Build settings
markdown:       cramdown

# About
author:
  name:         FirstName LastName
  email:        example@gmail.com

# Gems -> plugins
plugins:
  - jekyll-paginate 
